name: Python Package Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PYTHON_VERSION: '3.11'

{% raw -%}
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip dependencies and hatch environments
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.local/share/hatch
            ${{ env.pythonLocation }}/bin
            ${{ env.pythonLocation }}/lib/python${{ env.PYTHON_VERSION }}/site-packages
          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pip-hatch-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pip-hatch-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install -U pip
          python -m pip install hatch

      - name: Check code style
        run: hatch run style:check

      - name: Check type hints
        run: hatch run types:check

      - name: Perform static code analysis
        run: hatch run lint:check

      - name: Run unit tests
        run: hatch test -v --all --cover

      - name: Generate docs
        run: hatch run docs:build

      - name: Generate package
        run: hatch build
{%- endraw %}
