[tool.black]
line-length = 79

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
follow_imports = skip
no_implicit_optional = true
show_column_numbers = true
warn_no_return = true
